/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    products: Product;
    solutions: Solution;
    applications: Application;
    'blog-posts': BlogPost;
    'case-studies': CaseStudy;
    categories: Category;
    tags: Tag;
    faqs: Faq;
    enquiries: Enquiry;
    menus: Menu;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    solutions: SolutionsSelect<false> | SolutionsSelect<true>;
    applications: ApplicationsSelect<false> | ApplicationsSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    menus: MenusSelect<false> | MenusSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    header: Header;
    footer: Footer;
    'home-page': HomePage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  role?: ('admin' | 'editor') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  caption?: string | null;
  cloudinaryPublicId?: string | null;
  cloudinaryUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      cloudinaryPublicId?: string | null;
      cloudinaryUrl?: string | null;
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      cloudinaryPublicId?: string | null;
      cloudinaryUrl?: string | null;
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      cloudinaryPublicId?: string | null;
      cloudinaryUrl?: string | null;
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  /**
   * Clean SEO URL slug. Auto-generate from title, then edit manually if needed.
   */
  slug: string;
  excerpt?: string | null;
  layout?:
    | (
        | {
            eyebrow?: string | null;
            title: string;
            subtitle?: string | null;
            primaryCta?: {
              label?: string | null;
              url?: string | null;
            };
            secondaryCta?: {
              label?: string | null;
              url?: string | null;
            };
            image?: (string | null) | Media;
            dashboardPreview?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textBlock';
          }
        | {
            heading: string;
            body?: string | null;
            image?: (string | null) | Media;
            imagePosition?: ('left' | 'right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageText';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            features?:
              | {
                  title: string;
                  description?: string | null;
                  icon?: ('drop' | 'sensor' | 'cloud' | 'ai' | 'alert' | 'chart' | 'shield' | 'leaf') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureGrid';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            products?: (string | Product)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'productGrid';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            solutions?: (string | Solution)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'solutionGrid';
          }
        | {
            stats?:
              | {
                  label: string;
                  value: string;
                  note?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            description?: string | null;
            image?: (string | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'dashboardPreview';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            description?: string | null;
            button?: {
              label?: string | null;
              url?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            heading?: string | null;
            faqs?: (string | Faq)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            heading?: string | null;
            description?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactForm';
          }
        | {
            heading?: string | null;
            posts?: (string | BlogPost)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'blogGrid';
          }
        | {
            heading?: string | null;
            caseStudies?: (string | CaseStudy)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'caseStudyGrid';
          }
      )[]
    | null;
  pageType?: ('WebPage' | 'AboutPage' | 'ContactPage' | 'CollectionPage') | null;
  schema?: {
    schemaType?:
      | (
          | 'WebPage'
          | 'Product'
          | 'Service'
          | 'Article'
          | 'BlogPosting'
          | 'ContactPage'
          | 'AboutPage'
          | 'CollectionPage'
          | 'BreadcrumbList'
          | 'Organization'
          | 'LocalBusiness'
        )
      | null;
    /**
     * Optional custom JSON-LD. Avoid fake ratings, reviews, prices, awards or certifications.
     */
    customJsonLd?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  status: 'draft' | 'published' | 'scheduled';
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    focusKeyword?: string | null;
    secondaryKeywords?:
      | {
          keyword: string;
          id?: string | null;
        }[]
      | null;
    canonicalUrl?: string | null;
    robotsNoIndex?: boolean | null;
    robotsNoFollow?: boolean | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (string | null) | Media;
    twitterTitle?: string | null;
    twitterDescription?: string | null;
    twitterImage?: (string | null) | Media;
    schemaType?:
      | (
          | 'WebPage'
          | 'Product'
          | 'Service'
          | 'Article'
          | 'BlogPosting'
          | 'ContactPage'
          | 'AboutPage'
          | 'CollectionPage'
          | 'BreadcrumbList'
          | 'Organization'
          | 'LocalBusiness'
        )
      | null;
    /**
     * Optional custom JSON-LD. Avoid fake ratings, reviews, prices, awards or certifications.
     */
    customJsonLd?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Practical editorial checklist score inspired by SEO tools; not a Yoast/RankMath equivalent.
     */
    seoScore?: ('poor' | 'ok' | 'good' | 'excellent') | null;
    seoChecklist?: {
      keywordUsedInTitle?: boolean | null;
      keywordUsedInSlug?: boolean | null;
      keywordUsedInIntro?: boolean | null;
      hasInternalLinks?: boolean | null;
      hasExternalLinks?: boolean | null;
      hasImageAltText?: boolean | null;
      goodHeadingStructure?: boolean | null;
      healthyWordCount?: boolean | null;
      readabilityNotes?: string | null;
    };
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  name: string;
  /**
   * Clean SEO URL slug. Auto-generate from title, then edit manually if needed.
   */
  slug: string;
  subtitle?: string | null;
  shortDescription: string;
  longDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredImage?: (string | null) | Media;
  gallery?: (string | Media)[] | null;
  keyFeatures?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  technicalParameters?:
    | {
        parameter: string;
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  useCases?:
    | {
        useCase: string;
        id?: string | null;
      }[]
    | null;
  applications?: (string | Application)[] | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  brochure?: (string | null) | Media;
  relatedSolutions?: (string | Solution)[] | null;
  relatedBlogs?: (string | BlogPost)[] | null;
  schema?: {
    schemaType?:
      | (
          | 'WebPage'
          | 'Product'
          | 'Service'
          | 'Article'
          | 'BlogPosting'
          | 'ContactPage'
          | 'AboutPage'
          | 'CollectionPage'
          | 'BreadcrumbList'
          | 'Organization'
          | 'LocalBusiness'
        )
      | null;
    /**
     * Optional custom JSON-LD. Avoid fake ratings, reviews, prices, awards or certifications.
     */
    customJsonLd?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  status: 'draft' | 'published' | 'scheduled';
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    focusKeyword?: string | null;
    secondaryKeywords?:
      | {
          keyword: string;
          id?: string | null;
        }[]
      | null;
    canonicalUrl?: string | null;
    robotsNoIndex?: boolean | null;
    robotsNoFollow?: boolean | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (string | null) | Media;
    twitterTitle?: string | null;
    twitterDescription?: string | null;
    twitterImage?: (string | null) | Media;
    schemaType?:
      | (
          | 'WebPage'
          | 'Product'
          | 'Service'
          | 'Article'
          | 'BlogPosting'
          | 'ContactPage'
          | 'AboutPage'
          | 'CollectionPage'
          | 'BreadcrumbList'
          | 'Organization'
          | 'LocalBusiness'
        )
      | null;
    /**
     * Optional custom JSON-LD. Avoid fake ratings, reviews, prices, awards or certifications.
     */
    customJsonLd?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Practical editorial checklist score inspired by SEO tools; not a Yoast/RankMath equivalent.
     */
    seoScore?: ('poor' | 'ok' | 'good' | 'excellent') | null;
    seoChecklist?: {
      keywordUsedInTitle?: boolean | null;
      keywordUsedInSlug?: boolean | null;
      keywordUsedInIntro?: boolean | null;
      hasInternalLinks?: boolean | null;
      hasExternalLinks?: boolean | null;
      hasImageAltText?: boolean | null;
      goodHeadingStructure?: boolean | null;
      healthyWordCount?: boolean | null;
      readabilityNotes?: string | null;
    };
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications".
 */
export interface Application {
  id: string;
  name: string;
  /**
   * Clean SEO URL slug. Auto-generate from title, then edit manually if needed.
   */
  slug: string;
  shortDescription: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  sectors?:
    | {
        sector: string;
        id?: string | null;
      }[]
    | null;
  relatedSolutions?: (string | Solution)[] | null;
  schema?: {
    schemaType?:
      | (
          | 'WebPage'
          | 'Product'
          | 'Service'
          | 'Article'
          | 'BlogPosting'
          | 'ContactPage'
          | 'AboutPage'
          | 'CollectionPage'
          | 'BreadcrumbList'
          | 'Organization'
          | 'LocalBusiness'
        )
      | null;
    /**
     * Optional custom JSON-LD. Avoid fake ratings, reviews, prices, awards or certifications.
     */
    customJsonLd?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  status: 'draft' | 'published' | 'scheduled';
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    focusKeyword?: string | null;
    secondaryKeywords?:
      | {
          keyword: string;
          id?: string | null;
        }[]
      | null;
    canonicalUrl?: string | null;
    robotsNoIndex?: boolean | null;
    robotsNoFollow?: boolean | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (string | null) | Media;
    twitterTitle?: string | null;
    twitterDescription?: string | null;
    twitterImage?: (string | null) | Media;
    schemaType?:
      | (
          | 'WebPage'
          | 'Product'
          | 'Service'
          | 'Article'
          | 'BlogPosting'
          | 'ContactPage'
          | 'AboutPage'
          | 'CollectionPage'
          | 'BreadcrumbList'
          | 'Organization'
          | 'LocalBusiness'
        )
      | null;
    /**
     * Optional custom JSON-LD. Avoid fake ratings, reviews, prices, awards or certifications.
     */
    customJsonLd?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Practical editorial checklist score inspired by SEO tools; not a Yoast/RankMath equivalent.
     */
    seoScore?: ('poor' | 'ok' | 'good' | 'excellent') | null;
    seoChecklist?: {
      keywordUsedInTitle?: boolean | null;
      keywordUsedInSlug?: boolean | null;
      keywordUsedInIntro?: boolean | null;
      hasInternalLinks?: boolean | null;
      hasExternalLinks?: boolean | null;
      hasImageAltText?: boolean | null;
      goodHeadingStructure?: boolean | null;
      healthyWordCount?: boolean | null;
      readabilityNotes?: string | null;
    };
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions".
 */
export interface Solution {
  id: string;
  name: string;
  /**
   * Clean SEO URL slug. Auto-generate from title, then edit manually if needed.
   */
  slug: string;
  heroHeading?: string | null;
  shortDescription: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  benefits?:
    | {
        benefit: string;
        id?: string | null;
      }[]
    | null;
  process?:
    | {
        step: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  relatedProducts?: (string | Product)[] | null;
  relatedApplications?: (string | Application)[] | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  schema?: {
    schemaType?:
      | (
          | 'WebPage'
          | 'Product'
          | 'Service'
          | 'Article'
          | 'BlogPosting'
          | 'ContactPage'
          | 'AboutPage'
          | 'CollectionPage'
          | 'BreadcrumbList'
          | 'Organization'
          | 'LocalBusiness'
        )
      | null;
    /**
     * Optional custom JSON-LD. Avoid fake ratings, reviews, prices, awards or certifications.
     */
    customJsonLd?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  status: 'draft' | 'published' | 'scheduled';
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    focusKeyword?: string | null;
    secondaryKeywords?:
      | {
          keyword: string;
          id?: string | null;
        }[]
      | null;
    canonicalUrl?: string | null;
    robotsNoIndex?: boolean | null;
    robotsNoFollow?: boolean | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (string | null) | Media;
    twitterTitle?: string | null;
    twitterDescription?: string | null;
    twitterImage?: (string | null) | Media;
    schemaType?:
      | (
          | 'WebPage'
          | 'Product'
          | 'Service'
          | 'Article'
          | 'BlogPosting'
          | 'ContactPage'
          | 'AboutPage'
          | 'CollectionPage'
          | 'BreadcrumbList'
          | 'Organization'
          | 'LocalBusiness'
        )
      | null;
    /**
     * Optional custom JSON-LD. Avoid fake ratings, reviews, prices, awards or certifications.
     */
    customJsonLd?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Practical editorial checklist score inspired by SEO tools; not a Yoast/RankMath equivalent.
     */
    seoScore?: ('poor' | 'ok' | 'good' | 'excellent') | null;
    seoChecklist?: {
      keywordUsedInTitle?: boolean | null;
      keywordUsedInSlug?: boolean | null;
      keywordUsedInIntro?: boolean | null;
      hasInternalLinks?: boolean | null;
      hasExternalLinks?: boolean | null;
      hasImageAltText?: boolean | null;
      goodHeadingStructure?: boolean | null;
      healthyWordCount?: boolean | null;
      readabilityNotes?: string | null;
    };
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: string;
  title: string;
  /**
   * Clean SEO URL slug. Auto-generate from title, then edit manually if needed.
   */
  slug: string;
  excerpt: string;
  featuredImage?: (string | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  author?: string | null;
  category?: (string | null) | Category;
  tags?: (string | Tag)[] | null;
  /**
   * Can be generated from heading blocks during publishing.
   */
  tableOfContents?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Example: 4 min read
   */
  readingTime?: string | null;
  publishedDate?: string | null;
  modifiedDate?: string | null;
  relatedProducts?: (string | Product)[] | null;
  relatedSolutions?: (string | Solution)[] | null;
  relatedPosts?: (string | BlogPost)[] | null;
  focusKeyword?: string | null;
  secondaryKeywords?:
    | {
        keyword: string;
        id?: string | null;
      }[]
    | null;
  seoHelper?: {
    seoTitleLength?: number | null;
    metaDescriptionLength?: number | null;
    keywordUsageNotes?: string | null;
    slugQualityNotes?: string | null;
    headingStructureNotes?: string | null;
    internalLinkSuggestions?: string | null;
    externalLinkNotes?: string | null;
    imageAltTextReminder?: boolean | null;
    wordCount?: number | null;
    readabilityHints?: string | null;
    checklistScore?: ('poor' | 'ok' | 'good' | 'excellent') | null;
  };
  schema?: {
    schemaType?:
      | (
          | 'WebPage'
          | 'Product'
          | 'Service'
          | 'Article'
          | 'BlogPosting'
          | 'ContactPage'
          | 'AboutPage'
          | 'CollectionPage'
          | 'BreadcrumbList'
          | 'Organization'
          | 'LocalBusiness'
        )
      | null;
    /**
     * Optional custom JSON-LD. Avoid fake ratings, reviews, prices, awards or certifications.
     */
    customJsonLd?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  status: 'draft' | 'published' | 'scheduled';
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    focusKeyword?: string | null;
    secondaryKeywords?:
      | {
          keyword: string;
          id?: string | null;
        }[]
      | null;
    canonicalUrl?: string | null;
    robotsNoIndex?: boolean | null;
    robotsNoFollow?: boolean | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (string | null) | Media;
    twitterTitle?: string | null;
    twitterDescription?: string | null;
    twitterImage?: (string | null) | Media;
    schemaType?:
      | (
          | 'WebPage'
          | 'Product'
          | 'Service'
          | 'Article'
          | 'BlogPosting'
          | 'ContactPage'
          | 'AboutPage'
          | 'CollectionPage'
          | 'BreadcrumbList'
          | 'Organization'
          | 'LocalBusiness'
        )
      | null;
    /**
     * Optional custom JSON-LD. Avoid fake ratings, reviews, prices, awards or certifications.
     */
    customJsonLd?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Practical editorial checklist score inspired by SEO tools; not a Yoast/RankMath equivalent.
     */
    seoScore?: ('poor' | 'ok' | 'good' | 'excellent') | null;
    seoChecklist?: {
      keywordUsedInTitle?: boolean | null;
      keywordUsedInSlug?: boolean | null;
      keywordUsedInIntro?: boolean | null;
      hasInternalLinks?: boolean | null;
      hasExternalLinks?: boolean | null;
      hasImageAltText?: boolean | null;
      goodHeadingStructure?: boolean | null;
      healthyWordCount?: boolean | null;
      readabilityNotes?: string | null;
    };
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  name: string;
  /**
   * Clean SEO URL slug. Auto-generate from title, then edit manually if needed.
   */
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: string;
  name: string;
  /**
   * Clean SEO URL slug. Auto-generate from title, then edit manually if needed.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: string;
  question: string;
  answer: string;
  scope?: ('global' | 'page' | 'product' | 'solution' | 'blog') | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: string;
  title: string;
  /**
   * Clean SEO URL slug. Auto-generate from title, then edit manually if needed.
   */
  slug: string;
  industry?: string | null;
  excerpt?: string | null;
  problem?: string | null;
  solution?: string | null;
  /**
   * Use only verified outcomes. Avoid fake claims.
   */
  results?: string | null;
  images?: (string | Media)[] | null;
  relatedProducts?: (string | Product)[] | null;
  relatedSolutions?: (string | Solution)[] | null;
  schema?: {
    schemaType?:
      | (
          | 'WebPage'
          | 'Product'
          | 'Service'
          | 'Article'
          | 'BlogPosting'
          | 'ContactPage'
          | 'AboutPage'
          | 'CollectionPage'
          | 'BreadcrumbList'
          | 'Organization'
          | 'LocalBusiness'
        )
      | null;
    /**
     * Optional custom JSON-LD. Avoid fake ratings, reviews, prices, awards or certifications.
     */
    customJsonLd?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  status: 'draft' | 'published' | 'scheduled';
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    focusKeyword?: string | null;
    secondaryKeywords?:
      | {
          keyword: string;
          id?: string | null;
        }[]
      | null;
    canonicalUrl?: string | null;
    robotsNoIndex?: boolean | null;
    robotsNoFollow?: boolean | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (string | null) | Media;
    twitterTitle?: string | null;
    twitterDescription?: string | null;
    twitterImage?: (string | null) | Media;
    schemaType?:
      | (
          | 'WebPage'
          | 'Product'
          | 'Service'
          | 'Article'
          | 'BlogPosting'
          | 'ContactPage'
          | 'AboutPage'
          | 'CollectionPage'
          | 'BreadcrumbList'
          | 'Organization'
          | 'LocalBusiness'
        )
      | null;
    /**
     * Optional custom JSON-LD. Avoid fake ratings, reviews, prices, awards or certifications.
     */
    customJsonLd?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Practical editorial checklist score inspired by SEO tools; not a Yoast/RankMath equivalent.
     */
    seoScore?: ('poor' | 'ok' | 'good' | 'excellent') | null;
    seoChecklist?: {
      keywordUsedInTitle?: boolean | null;
      keywordUsedInSlug?: boolean | null;
      keywordUsedInIntro?: boolean | null;
      hasInternalLinks?: boolean | null;
      hasExternalLinks?: boolean | null;
      hasImageAltText?: boolean | null;
      goodHeadingStructure?: boolean | null;
      healthyWordCount?: boolean | null;
      readabilityNotes?: string | null;
    };
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: string;
  name: string;
  company?: string | null;
  email: string;
  phone?: string | null;
  country: string;
  requirementType: string;
  interest?: string | null;
  sourcePage?: string | null;
  message: string;
  consent: boolean;
  website?: string | null;
  status?: ('new' | 'contacted' | 'converted' | 'closed') | null;
  adminNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus".
 */
export interface Menu {
  id: string;
  name: string;
  location: 'header' | 'footer' | 'cta';
  items?:
    | {
        label: string;
        linkType?: ('internal' | 'external') | null;
        url: string;
        openInNewTab?: boolean | null;
        sortOrder?: number | null;
        published?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'solutions';
        value: string | Solution;
      } | null)
    | ({
        relationTo: 'applications';
        value: string | Application;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: string | BlogPost;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: string | CaseStudy;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: string | Tag;
      } | null)
    | ({
        relationTo: 'faqs';
        value: string | Faq;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: string | Enquiry;
      } | null)
    | ({
        relationTo: 'menus';
        value: string | Menu;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  cloudinaryPublicId?: T;
  cloudinaryUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              cloudinaryPublicId?: T;
              cloudinaryUrl?: T;
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              cloudinaryPublicId?: T;
              cloudinaryUrl?: T;
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              cloudinaryPublicId?: T;
              cloudinaryUrl?: T;
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              subtitle?: T;
              primaryCta?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              secondaryCta?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              image?: T;
              dashboardPreview?: T;
              id?: T;
              blockName?: T;
            };
        textBlock?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        imageText?:
          | T
          | {
              heading?: T;
              body?: T;
              image?: T;
              imagePosition?: T;
              id?: T;
              blockName?: T;
            };
        featureGrid?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              features?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        productGrid?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              products?: T;
              id?: T;
              blockName?: T;
            };
        solutionGrid?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              solutions?: T;
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              stats?:
                | T
                | {
                    label?: T;
                    value?: T;
                    note?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        dashboardPreview?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              button?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              heading?: T;
              faqs?: T;
              id?: T;
              blockName?: T;
            };
        contactForm?:
          | T
          | {
              heading?: T;
              description?: T;
              id?: T;
              blockName?: T;
            };
        blogGrid?:
          | T
          | {
              heading?: T;
              posts?: T;
              id?: T;
              blockName?: T;
            };
        caseStudyGrid?:
          | T
          | {
              heading?: T;
              caseStudies?: T;
              id?: T;
              blockName?: T;
            };
      };
  pageType?: T;
  schema?:
    | T
    | {
        schemaType?: T;
        customJsonLd?: T;
      };
  status?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        focusKeyword?: T;
        secondaryKeywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
        canonicalUrl?: T;
        robotsNoIndex?: T;
        robotsNoFollow?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        twitterTitle?: T;
        twitterDescription?: T;
        twitterImage?: T;
        schemaType?: T;
        customJsonLd?: T;
        seoScore?: T;
        seoChecklist?:
          | T
          | {
              keywordUsedInTitle?: T;
              keywordUsedInSlug?: T;
              keywordUsedInIntro?: T;
              hasInternalLinks?: T;
              hasExternalLinks?: T;
              hasImageAltText?: T;
              goodHeadingStructure?: T;
              healthyWordCount?: T;
              readabilityNotes?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  subtitle?: T;
  shortDescription?: T;
  longDescription?: T;
  featuredImage?: T;
  gallery?: T;
  keyFeatures?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  technicalParameters?:
    | T
    | {
        parameter?: T;
        value?: T;
        id?: T;
      };
  useCases?:
    | T
    | {
        useCase?: T;
        id?: T;
      };
  applications?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  brochure?: T;
  relatedSolutions?: T;
  relatedBlogs?: T;
  schema?:
    | T
    | {
        schemaType?: T;
        customJsonLd?: T;
      };
  status?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        focusKeyword?: T;
        secondaryKeywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
        canonicalUrl?: T;
        robotsNoIndex?: T;
        robotsNoFollow?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        twitterTitle?: T;
        twitterDescription?: T;
        twitterImage?: T;
        schemaType?: T;
        customJsonLd?: T;
        seoScore?: T;
        seoChecklist?:
          | T
          | {
              keywordUsedInTitle?: T;
              keywordUsedInSlug?: T;
              keywordUsedInIntro?: T;
              hasInternalLinks?: T;
              hasExternalLinks?: T;
              hasImageAltText?: T;
              goodHeadingStructure?: T;
              healthyWordCount?: T;
              readabilityNotes?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions_select".
 */
export interface SolutionsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  heroHeading?: T;
  shortDescription?: T;
  content?: T;
  benefits?:
    | T
    | {
        benefit?: T;
        id?: T;
      };
  process?:
    | T
    | {
        step?: T;
        description?: T;
        id?: T;
      };
  relatedProducts?: T;
  relatedApplications?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  schema?:
    | T
    | {
        schemaType?: T;
        customJsonLd?: T;
      };
  status?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        focusKeyword?: T;
        secondaryKeywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
        canonicalUrl?: T;
        robotsNoIndex?: T;
        robotsNoFollow?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        twitterTitle?: T;
        twitterDescription?: T;
        twitterImage?: T;
        schemaType?: T;
        customJsonLd?: T;
        seoScore?: T;
        seoChecklist?:
          | T
          | {
              keywordUsedInTitle?: T;
              keywordUsedInSlug?: T;
              keywordUsedInIntro?: T;
              hasInternalLinks?: T;
              hasExternalLinks?: T;
              hasImageAltText?: T;
              goodHeadingStructure?: T;
              healthyWordCount?: T;
              readabilityNotes?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications_select".
 */
export interface ApplicationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  shortDescription?: T;
  content?: T;
  sectors?:
    | T
    | {
        sector?: T;
        id?: T;
      };
  relatedSolutions?: T;
  schema?:
    | T
    | {
        schemaType?: T;
        customJsonLd?: T;
      };
  status?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        focusKeyword?: T;
        secondaryKeywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
        canonicalUrl?: T;
        robotsNoIndex?: T;
        robotsNoFollow?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        twitterTitle?: T;
        twitterDescription?: T;
        twitterImage?: T;
        schemaType?: T;
        customJsonLd?: T;
        seoScore?: T;
        seoChecklist?:
          | T
          | {
              keywordUsedInTitle?: T;
              keywordUsedInSlug?: T;
              keywordUsedInIntro?: T;
              hasInternalLinks?: T;
              hasExternalLinks?: T;
              hasImageAltText?: T;
              goodHeadingStructure?: T;
              healthyWordCount?: T;
              readabilityNotes?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  featuredImage?: T;
  content?: T;
  author?: T;
  category?: T;
  tags?: T;
  tableOfContents?: T;
  readingTime?: T;
  publishedDate?: T;
  modifiedDate?: T;
  relatedProducts?: T;
  relatedSolutions?: T;
  relatedPosts?: T;
  focusKeyword?: T;
  secondaryKeywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  seoHelper?:
    | T
    | {
        seoTitleLength?: T;
        metaDescriptionLength?: T;
        keywordUsageNotes?: T;
        slugQualityNotes?: T;
        headingStructureNotes?: T;
        internalLinkSuggestions?: T;
        externalLinkNotes?: T;
        imageAltTextReminder?: T;
        wordCount?: T;
        readabilityHints?: T;
        checklistScore?: T;
      };
  schema?:
    | T
    | {
        schemaType?: T;
        customJsonLd?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  status?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        focusKeyword?: T;
        secondaryKeywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
        canonicalUrl?: T;
        robotsNoIndex?: T;
        robotsNoFollow?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        twitterTitle?: T;
        twitterDescription?: T;
        twitterImage?: T;
        schemaType?: T;
        customJsonLd?: T;
        seoScore?: T;
        seoChecklist?:
          | T
          | {
              keywordUsedInTitle?: T;
              keywordUsedInSlug?: T;
              keywordUsedInIntro?: T;
              hasInternalLinks?: T;
              hasExternalLinks?: T;
              hasImageAltText?: T;
              goodHeadingStructure?: T;
              healthyWordCount?: T;
              readabilityNotes?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  industry?: T;
  excerpt?: T;
  problem?: T;
  solution?: T;
  results?: T;
  images?: T;
  relatedProducts?: T;
  relatedSolutions?: T;
  schema?:
    | T
    | {
        schemaType?: T;
        customJsonLd?: T;
      };
  status?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        focusKeyword?: T;
        secondaryKeywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
        canonicalUrl?: T;
        robotsNoIndex?: T;
        robotsNoFollow?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        twitterTitle?: T;
        twitterDescription?: T;
        twitterImage?: T;
        schemaType?: T;
        customJsonLd?: T;
        seoScore?: T;
        seoChecklist?:
          | T
          | {
              keywordUsedInTitle?: T;
              keywordUsedInSlug?: T;
              keywordUsedInIntro?: T;
              hasInternalLinks?: T;
              hasExternalLinks?: T;
              hasImageAltText?: T;
              goodHeadingStructure?: T;
              healthyWordCount?: T;
              readabilityNotes?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  scope?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  name?: T;
  company?: T;
  email?: T;
  phone?: T;
  country?: T;
  requirementType?: T;
  interest?: T;
  sourcePage?: T;
  message?: T;
  consent?: T;
  website?: T;
  status?: T;
  adminNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus_select".
 */
export interface MenusSelect<T extends boolean = true> {
  name?: T;
  location?: T;
  items?:
    | T
    | {
        label?: T;
        linkType?: T;
        url?: T;
        openInNewTab?: T;
        sortOrder?: T;
        published?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  siteName: string;
  logo?: (string | null) | Media;
  favicon?: (string | null) | Media;
  defaultOgImage?: (string | null) | Media;
  businessEmail?: string | null;
  phoneNumber?: string | null;
  address?: string | null;
  socialLinks?:
    | {
        label: string;
        linkType?: ('internal' | 'external') | null;
        url: string;
        openInNewTab?: boolean | null;
        sortOrder?: number | null;
        published?: boolean | null;
        id?: string | null;
      }[]
    | null;
  headerCta: {
    label: string;
    linkType?: ('internal' | 'external') | null;
    url: string;
  };
  footerText?: string | null;
  globalSeoDefaults?: {
    focusKeyword?: string | null;
    secondaryKeywords?:
      | {
          keyword: string;
          id?: string | null;
        }[]
      | null;
    canonicalUrl?: string | null;
    robotsNoIndex?: boolean | null;
    robotsNoFollow?: boolean | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (string | null) | Media;
    twitterTitle?: string | null;
    twitterDescription?: string | null;
    twitterImage?: (string | null) | Media;
    schemaType?:
      | (
          | 'WebPage'
          | 'Product'
          | 'Service'
          | 'Article'
          | 'BlogPosting'
          | 'ContactPage'
          | 'AboutPage'
          | 'CollectionPage'
          | 'BreadcrumbList'
          | 'Organization'
          | 'LocalBusiness'
        )
      | null;
    /**
     * Optional custom JSON-LD. Avoid fake ratings, reviews, prices, awards or certifications.
     */
    customJsonLd?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Practical editorial checklist score inspired by SEO tools; not a Yoast/RankMath equivalent.
     */
    seoScore?: ('poor' | 'ok' | 'good' | 'excellent') | null;
    seoChecklist?: {
      keywordUsedInTitle?: boolean | null;
      keywordUsedInSlug?: boolean | null;
      keywordUsedInIntro?: boolean | null;
      hasInternalLinks?: boolean | null;
      hasExternalLinks?: boolean | null;
      hasImageAltText?: boolean | null;
      goodHeadingStructure?: boolean | null;
      healthyWordCount?: boolean | null;
      readabilityNotes?: string | null;
    };
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    focusKeyword?: string | null;
    secondaryKeywords?:
      | {
          keyword: string;
          id?: string | null;
        }[]
      | null;
    canonicalUrl?: string | null;
    robotsNoIndex?: boolean | null;
    robotsNoFollow?: boolean | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (string | null) | Media;
    twitterTitle?: string | null;
    twitterDescription?: string | null;
    twitterImage?: (string | null) | Media;
    schemaType?:
      | (
          | 'WebPage'
          | 'Product'
          | 'Service'
          | 'Article'
          | 'BlogPosting'
          | 'ContactPage'
          | 'AboutPage'
          | 'CollectionPage'
          | 'BreadcrumbList'
          | 'Organization'
          | 'LocalBusiness'
        )
      | null;
    /**
     * Optional custom JSON-LD. Avoid fake ratings, reviews, prices, awards or certifications.
     */
    customJsonLd?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Practical editorial checklist score inspired by SEO tools; not a Yoast/RankMath equivalent.
     */
    seoScore?: ('poor' | 'ok' | 'good' | 'excellent') | null;
    seoChecklist?: {
      keywordUsedInTitle?: boolean | null;
      keywordUsedInSlug?: boolean | null;
      keywordUsedInIntro?: boolean | null;
      hasInternalLinks?: boolean | null;
      hasExternalLinks?: boolean | null;
      hasImageAltText?: boolean | null;
      goodHeadingStructure?: boolean | null;
      healthyWordCount?: boolean | null;
      readabilityNotes?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  logo?: (string | null) | Media;
  menuItems?:
    | {
        label: string;
        linkType?: ('internal' | 'external') | null;
        url: string;
        openInNewTab?: boolean | null;
        sortOrder?: number | null;
        published?: boolean | null;
        id?: string | null;
      }[]
    | null;
  cta: {
    label: string;
    linkType?: ('internal' | 'external') | null;
    url: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  logo?: (string | null) | Media;
  description?: string | null;
  columns?:
    | {
        heading: string;
        links?:
          | {
              label: string;
              linkType?: ('internal' | 'external') | null;
              url: string;
              openInNewTab?: boolean | null;
              sortOrder?: number | null;
              published?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  bottomText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: string;
  hero?: {
    eyebrow?: string | null;
    title?: string | null;
    subtitle?: string | null;
    primaryCtaLabel?: string | null;
    primaryCtaUrl?: string | null;
    secondaryCtaLabel?: string | null;
    secondaryCtaUrl?: string | null;
    image?: (string | null) | Media;
    dashboardPreview?: boolean | null;
  };
  trustStats?:
    | {
        label?: string | null;
        note?: string | null;
        icon?: ('drop' | 'chart' | 'shield' | 'cloud') | null;
        id?: string | null;
      }[]
    | null;
  sections?:
    | (
        | {
            eyebrow?: string | null;
            title: string;
            subtitle?: string | null;
            primaryCta?: {
              label?: string | null;
              url?: string | null;
            };
            secondaryCta?: {
              label?: string | null;
              url?: string | null;
            };
            image?: (string | null) | Media;
            dashboardPreview?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textBlock';
          }
        | {
            heading: string;
            body?: string | null;
            image?: (string | null) | Media;
            imagePosition?: ('left' | 'right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageText';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            features?:
              | {
                  title: string;
                  description?: string | null;
                  icon?: ('drop' | 'sensor' | 'cloud' | 'ai' | 'alert' | 'chart' | 'shield' | 'leaf') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureGrid';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            products?: (string | Product)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'productGrid';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            solutions?: (string | Solution)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'solutionGrid';
          }
        | {
            stats?:
              | {
                  label: string;
                  value: string;
                  note?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            description?: string | null;
            image?: (string | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'dashboardPreview';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            description?: string | null;
            button?: {
              label?: string | null;
              url?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            heading?: string | null;
            faqs?: (string | Faq)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            heading?: string | null;
            description?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactForm';
          }
        | {
            heading?: string | null;
            posts?: (string | BlogPost)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'blogGrid';
          }
        | {
            heading?: string | null;
            caseStudies?: (string | CaseStudy)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'caseStudyGrid';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    focusKeyword?: string | null;
    secondaryKeywords?:
      | {
          keyword: string;
          id?: string | null;
        }[]
      | null;
    canonicalUrl?: string | null;
    robotsNoIndex?: boolean | null;
    robotsNoFollow?: boolean | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (string | null) | Media;
    twitterTitle?: string | null;
    twitterDescription?: string | null;
    twitterImage?: (string | null) | Media;
    schemaType?:
      | (
          | 'WebPage'
          | 'Product'
          | 'Service'
          | 'Article'
          | 'BlogPosting'
          | 'ContactPage'
          | 'AboutPage'
          | 'CollectionPage'
          | 'BreadcrumbList'
          | 'Organization'
          | 'LocalBusiness'
        )
      | null;
    /**
     * Optional custom JSON-LD. Avoid fake ratings, reviews, prices, awards or certifications.
     */
    customJsonLd?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Practical editorial checklist score inspired by SEO tools; not a Yoast/RankMath equivalent.
     */
    seoScore?: ('poor' | 'ok' | 'good' | 'excellent') | null;
    seoChecklist?: {
      keywordUsedInTitle?: boolean | null;
      keywordUsedInSlug?: boolean | null;
      keywordUsedInIntro?: boolean | null;
      hasInternalLinks?: boolean | null;
      hasExternalLinks?: boolean | null;
      hasImageAltText?: boolean | null;
      goodHeadingStructure?: boolean | null;
      healthyWordCount?: boolean | null;
      readabilityNotes?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  logo?: T;
  favicon?: T;
  defaultOgImage?: T;
  businessEmail?: T;
  phoneNumber?: T;
  address?: T;
  socialLinks?:
    | T
    | {
        label?: T;
        linkType?: T;
        url?: T;
        openInNewTab?: T;
        sortOrder?: T;
        published?: T;
        id?: T;
      };
  headerCta?:
    | T
    | {
        label?: T;
        linkType?: T;
        url?: T;
      };
  footerText?: T;
  globalSeoDefaults?:
    | T
    | {
        focusKeyword?: T;
        secondaryKeywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
        canonicalUrl?: T;
        robotsNoIndex?: T;
        robotsNoFollow?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        twitterTitle?: T;
        twitterDescription?: T;
        twitterImage?: T;
        schemaType?: T;
        customJsonLd?: T;
        seoScore?: T;
        seoChecklist?:
          | T
          | {
              keywordUsedInTitle?: T;
              keywordUsedInSlug?: T;
              keywordUsedInIntro?: T;
              hasInternalLinks?: T;
              hasExternalLinks?: T;
              hasImageAltText?: T;
              goodHeadingStructure?: T;
              healthyWordCount?: T;
              readabilityNotes?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        focusKeyword?: T;
        secondaryKeywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
        canonicalUrl?: T;
        robotsNoIndex?: T;
        robotsNoFollow?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        twitterTitle?: T;
        twitterDescription?: T;
        twitterImage?: T;
        schemaType?: T;
        customJsonLd?: T;
        seoScore?: T;
        seoChecklist?:
          | T
          | {
              keywordUsedInTitle?: T;
              keywordUsedInSlug?: T;
              keywordUsedInIntro?: T;
              hasInternalLinks?: T;
              hasExternalLinks?: T;
              hasImageAltText?: T;
              goodHeadingStructure?: T;
              healthyWordCount?: T;
              readabilityNotes?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  menuItems?:
    | T
    | {
        label?: T;
        linkType?: T;
        url?: T;
        openInNewTab?: T;
        sortOrder?: T;
        published?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        linkType?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?: T;
  description?: T;
  columns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              linkType?: T;
              url?: T;
              openInNewTab?: T;
              sortOrder?: T;
              published?: T;
              id?: T;
            };
        id?: T;
      };
  bottomText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        primaryCtaLabel?: T;
        primaryCtaUrl?: T;
        secondaryCtaLabel?: T;
        secondaryCtaUrl?: T;
        image?: T;
        dashboardPreview?: T;
      };
  trustStats?:
    | T
    | {
        label?: T;
        note?: T;
        icon?: T;
        id?: T;
      };
  sections?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              subtitle?: T;
              primaryCta?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              secondaryCta?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              image?: T;
              dashboardPreview?: T;
              id?: T;
              blockName?: T;
            };
        textBlock?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        imageText?:
          | T
          | {
              heading?: T;
              body?: T;
              image?: T;
              imagePosition?: T;
              id?: T;
              blockName?: T;
            };
        featureGrid?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              features?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        productGrid?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              products?: T;
              id?: T;
              blockName?: T;
            };
        solutionGrid?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              solutions?: T;
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              stats?:
                | T
                | {
                    label?: T;
                    value?: T;
                    note?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        dashboardPreview?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              button?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              heading?: T;
              faqs?: T;
              id?: T;
              blockName?: T;
            };
        contactForm?:
          | T
          | {
              heading?: T;
              description?: T;
              id?: T;
              blockName?: T;
            };
        blogGrid?:
          | T
          | {
              heading?: T;
              posts?: T;
              id?: T;
              blockName?: T;
            };
        caseStudyGrid?:
          | T
          | {
              heading?: T;
              caseStudies?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        focusKeyword?: T;
        secondaryKeywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
        canonicalUrl?: T;
        robotsNoIndex?: T;
        robotsNoFollow?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        twitterTitle?: T;
        twitterDescription?: T;
        twitterImage?: T;
        schemaType?: T;
        customJsonLd?: T;
        seoScore?: T;
        seoChecklist?:
          | T
          | {
              keywordUsedInTitle?: T;
              keywordUsedInSlug?: T;
              keywordUsedInIntro?: T;
              hasInternalLinks?: T;
              hasExternalLinks?: T;
              hasImageAltText?: T;
              goodHeadingStructure?: T;
              healthyWordCount?: T;
              readabilityNotes?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}